# This is a basic workflow to help you get started with Actions

name: 'Push readme to dockerhub'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      #- name: setup-docker
      #  uses: docker-practice/actions-setup-docker@1.0.8

      - name: Push readme
        run: |
          DOCKERHUB_REPO_NAME=${GITHUB_REPOSITORY#*/}
          docker run --rm  -v $(pwd)/README.md:/data/README.md -e DOCKERHUB_USERNAME=${{ secrets.DOCKER_USERNAME }} -e DOCKERHUB_PASSWORD=${{ secrets.DOCKER_PASSWORD }} -e DOCKERHUB_REPO_PREFIX=${{ secrets.DOCKER_USERNAME }} -e DOCKERHUB_REPO_NAME=$DOCKERHUB_REPO_NAME sheogorath/readme-to-dockerhub
          
